# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/noahshao/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/nxxxsooo"

[social.params]
icon = "brand-x"
